# action.yml
name: Create a github.go file
description: Create a github.go file containing GitHub release information.
author: support@senzing.com

inputs:
   file:
      description: "The file to create. Default: cmd/github.go"
      required: false
      default: cmd/github.go
   package:
      description: "The package name for the package statement. Default: cmd"
      required: false
      default: cmd

runs:
   using: composite
   steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
           fetch-depth: "0"
      - name: run file
        run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.file }} ${{ inputs.package }}
        shell: bash
        env:
           GH_TOKEN: ${{ github.token }}

branding:
   icon: git-pull-request
   color: red
