# action.yml
name: "Create a version.go file"
description: "Create a version.go file containing the current GitHub release information."
author: support@senzing.com

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "git-pull-request"
  color: "red"
